In [1]:
import numpy as np

In [2]:
python_list=[1,2,3,5,-5]

In [3]:
python_list

[1, 2, 3, 5, -5]

In [6]:
numpy_arr = np.array(python_list)

In [7]:
numpy_arr.shape

(5,)

In [8]:
python_list_list=[[1,2],[3,4]]

In [9]:
python_list_list

[[1, 2], [3, 4]]

In [10]:
np.array(python_list_list)

array([[1, 2],
       [3, 4]])

In [11]:
numpy_arr2 = np.array(python_list_list)

In [12]:
numpy_arr2.shape

(2, 2)

In [13]:
len(numpy_arr2.shape)

2

In [14]:
list(range(5))

[0, 1, 2, 3, 4]

In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [16]:
np.zeros((2, 2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [17]:
np.random.randint(5)

4