In [2]:
import numpy as np

In [5]:
marks=[2,3,4,5],[6,7,8,9],[10,11,12,13]

In [6]:
marks_transpose=[]
for j in range(len(marks[0])):
    marks_transpose.append([])
    for i in range(len(marks)):
        marks_transpose[j].append(marks[i][j])

In [7]:
marks_transpose

[[2, 6, 10], [3, 7, 11], [4, 8, 12], [5, 9, 13]]

In [8]:
marks_array=np.array(marks)

In [9]:
marks_array

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [10]:
marks_array.T

array([[ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12],
       [ 5,  9, 13]])

In [11]:
marks_array.sum(axis=1)/60*100

array([23.33333333, 50.        , 76.66666667])

In [12]:
marks_array.T.sum(axis=1)

array([18, 21, 24, 27])

In [13]:
marks_array

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [14]:
grace_marks=np.array([[1,2,3]]).T

In [15]:
grace_marks.shape

(3, 1)