In [1]:
import numpy as np

In [2]:
arr=np.random.rand(5,5)

In [3]:
arr

array([[0.13841675, 0.56834059, 0.42272959, 0.94843325, 0.91155439],
       [0.09948654, 0.61145549, 0.74410254, 0.19612537, 0.21188191],
       [0.06319274, 0.96490332, 0.26715577, 0.96676265, 0.24949658],
       [0.22739495, 0.43036045, 0.50772144, 0.95242577, 0.91776708],
       [0.75846809, 0.06285758, 0.38734725, 0.05705082, 0.66868259]])

In [4]:
arr.shape

(5, 5)

In [5]:
arr.dtype

dtype('float64')

In [6]:
arr[:6]

array([[0.13841675, 0.56834059, 0.42272959, 0.94843325, 0.91155439],
       [0.09948654, 0.61145549, 0.74410254, 0.19612537, 0.21188191],
       [0.06319274, 0.96490332, 0.26715577, 0.96676265, 0.24949658],
       [0.22739495, 0.43036045, 0.50772144, 0.95242577, 0.91776708],
       [0.75846809, 0.06285758, 0.38734725, 0.05705082, 0.66868259]])

In [7]:
arr[:3]

array([[0.13841675, 0.56834059, 0.42272959, 0.94843325, 0.91155439],
       [0.09948654, 0.61145549, 0.74410254, 0.19612537, 0.21188191],
       [0.06319274, 0.96490332, 0.26715577, 0.96676265, 0.24949658]])

In [8]:
arr[:3, :5]

array([[0.13841675, 0.56834059, 0.42272959, 0.94843325, 0.91155439],
       [0.09948654, 0.61145549, 0.74410254, 0.19612537, 0.21188191],
       [0.06319274, 0.96490332, 0.26715577, 0.96676265, 0.24949658]])

In [9]:
arr[:2,:2]

array([[0.13841675, 0.56834059],
       [0.09948654, 0.61145549]])

In [10]:
arr[-3]

array([0.06319274, 0.96490332, 0.26715577, 0.96676265, 0.24949658])

In [11]:
arr[:-3]

array([[0.13841675, 0.56834059, 0.42272959, 0.94843325, 0.91155439],
       [0.09948654, 0.61145549, 0.74410254, 0.19612537, 0.21188191]])

In [12]:
arr2=np.random.randint(5,size=(6,8))

In [13]:
arr2

array([[0, 4, 2, 4, 2, 4, 4, 2],
       [0, 1, 2, 2, 1, 1, 3, 3],
       [2, 4, 4, 1, 2, 2, 0, 4],
       [0, 1, 0, 4, 0, 1, 0, 1],
       [1, 3, 0, 4, 3, 2, 0, 1],
       [0, 3, 3, 3, 1, 2, 3, 1]], dtype=int32)

In [14]:
marks=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [15]:
weights_list=[[0.4,0.2,0.2,0.2]]

In [16]:
marks.shape

AttributeError: 'list' object has no attribute 'shape'

In [17]:
marks_array=np.array(marks)

In [18]:
marks_array.shape

(3, 4)

In [19]:
weights_array=np.array(weights_array)

NameError: name 'weights_array' is not defined

In [20]:
weights_array=np.array(weights_list)

In [21]:
weights_array.list

AttributeError: 'numpy.ndarray' object has no attribute 'list'

In [22]:
weights_array.shape

(1, 4)

In [23]:
marks_array @ weights_array

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 4)

In [24]:
marks_array @ weights_array.T

array([[ 2.2],
       [ 6.2],
       [10.2]])